
CREATE TABLE teacher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_email VARCHAR(255) NOT NULL UNIQUE,
    teacher_name VARCHAR(255) NOT NULL,
    teacher_password VARCHAR(255) NOT NULL,
    teacher_role VARCHAR(20) NOT NULL
);

CREATE TABLE class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name VARCHAR(255) NOT NULL,
    class_year INTEGER NOT NULL,
    class_discipline VARCHAR(50) NOT NULL,
    class_shift VARCHAR(20) NOT NULL,
    teacher_id BIGINT NOT NULL,
    CONSTRAINT FK_CLASS_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher(id)
);

CREATE TABLE student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(255) NOT NULL,
    student_email VARCHAR(255) NOT NULL UNIQUE,
    student_password VARCHAR(255) NOT NULL,
    student_role VARCHAR(20) NOT NULL,
    student_final_grade DOUBLE,
    student_grades VARCHAR(20),
    is_student_passed BOOLEAN,
    class_id BIGINT,
    CONSTRAINT FK_STUDENT_CLASS FOREIGN KEY (class_id) REFERENCES class(id)
);